/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculatorapp;

/**
 *
 * @author Steven
 */
public class CalculatorAppFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalculatorAppFrame
     */
    public void setMessageBox(String msg, String title){
        msgHelp.showMessageDialog(this,msg,title, javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }
    public CalculatorAppFrame() {
        initComponents();
        this.setSize(350,435);      //565,425 on extended
        Menus toPlain = new Menus();
        toPlain.initialiseTxt(txtInOut);
        b.setDouble1();
        b.setDouble1();
        b.populateOps();
        b.startDisplay(txtInOut);
    }
    
    public void resetRound(){
        Menus rndReset = new Menus();
        rndReset.round(rnd9, txtInOut);        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grpView = new javax.swing.ButtonGroup();
        grpFont = new javax.swing.ButtonGroup();
        grpRound = new javax.swing.ButtonGroup();
        grpMode = new javax.swing.ButtonGroup();
        msgHelp = new javax.swing.JOptionPane();
        txtInOut = new javax.swing.JTextField();
        pnlStandard = new javax.swing.JPanel();
        btn1 = new javax.swing.JButton();
        btn2 = new javax.swing.JButton();
        btn3 = new javax.swing.JButton();
        btnMultiply = new javax.swing.JButton();
        btn1OverX = new javax.swing.JButton();
        btn4 = new javax.swing.JButton();
        btn5 = new javax.swing.JButton();
        btnDivide = new javax.swing.JButton();
        btnPower = new javax.swing.JButton();
        btn6 = new javax.swing.JButton();
        btn7 = new javax.swing.JButton();
        btn8 = new javax.swing.JButton();
        btnPlus = new javax.swing.JButton();
        btnSignFlip = new javax.swing.JButton();
        btn9 = new javax.swing.JButton();
        btnCA = new javax.swing.JButton();
        btnCE = new javax.swing.JButton();
        btn0 = new javax.swing.JButton();
        btnPoint = new javax.swing.JButton();
        btnEqual = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        btnFact = new javax.swing.JButton();
        pnlExtended = new javax.swing.JPanel();
        btnAsin = new javax.swing.JButton();
        btnSin = new javax.swing.JButton();
        btnCos = new javax.swing.JButton();
        btnAcos = new javax.swing.JButton();
        btnTan = new javax.swing.JButton();
        btnAtan = new javax.swing.JButton();
        btnPi = new javax.swing.JButton();
        btnE = new javax.swing.JButton();
        radRadians = new javax.swing.JRadioButton();
        radDegrees = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuView = new javax.swing.JMenu();
        mnuBasic = new javax.swing.JRadioButtonMenuItem();
        mnuExtended = new javax.swing.JRadioButtonMenuItem();
        mnuFont = new javax.swing.JMenu();
        mnuPlain = new javax.swing.JRadioButtonMenuItem();
        mnuBold = new javax.swing.JRadioButtonMenuItem();
        mnuRound = new javax.swing.JMenu();
        rnd0 = new javax.swing.JRadioButtonMenuItem();
        rnd1 = new javax.swing.JRadioButtonMenuItem();
        rnd2 = new javax.swing.JRadioButtonMenuItem();
        rnd3 = new javax.swing.JRadioButtonMenuItem();
        rnd4 = new javax.swing.JRadioButtonMenuItem();
        rnd5 = new javax.swing.JRadioButtonMenuItem();
        rnd6 = new javax.swing.JRadioButtonMenuItem();
        rnd7 = new javax.swing.JRadioButtonMenuItem();
        rnd8 = new javax.swing.JRadioButtonMenuItem();
        rnd9 = new javax.swing.JRadioButtonMenuItem();
        mnuHelp = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenuItem();
        mnuHotKeys = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        txtInOut.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtInOut.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtInOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInOutActionPerformed(evt);
            }
        });
        txtInOut.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtInOutKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtInOutKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInOutKeyTyped(evt);
            }
        });
        getContentPane().add(txtInOut);
        txtInOut.setBounds(10, 0, 320, 50);

        btn1.setText("1");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });

        btn2.setText("2");
        btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2ActionPerformed(evt);
            }
        });

        btn3.setText("3");
        btn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3ActionPerformed(evt);
            }
        });

        btnMultiply.setText("*");
        btnMultiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMultiplyActionPerformed(evt);
            }
        });

        btn1OverX.setText("1/x");
        btn1OverX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1OverXActionPerformed(evt);
            }
        });

        btn4.setText("4");
        btn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn4ActionPerformed(evt);
            }
        });

        btn5.setText("5");
        btn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn5ActionPerformed(evt);
            }
        });

        btnDivide.setText("/");
        btnDivide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDivideActionPerformed(evt);
            }
        });

        btnPower.setText("x^y");
        btnPower.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPowerActionPerformed(evt);
            }
        });

        btn6.setText("6");
        btn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn6ActionPerformed(evt);
            }
        });

        btn7.setText("7");
        btn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn7ActionPerformed(evt);
            }
        });

        btn8.setText("8");
        btn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn8ActionPerformed(evt);
            }
        });

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnSignFlip.setText("+/-");
        btnSignFlip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignFlipActionPerformed(evt);
            }
        });

        btn9.setText("9");
        btn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn9ActionPerformed(evt);
            }
        });

        btnCA.setText("CA");
        btnCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCAActionPerformed(evt);
            }
        });

        btnCE.setText("CE");
        btnCE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCEActionPerformed(evt);
            }
        });

        btn0.setText("0");
        btn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn0ActionPerformed(evt);
            }
        });

        btnPoint.setText(".");
        btnPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPointActionPerformed(evt);
            }
        });

        btnEqual.setText("=");
        btnEqual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEqualActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        btnFact.setText("x!");
        btnFact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFactActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlStandardLayout = new javax.swing.GroupLayout(pnlStandard);
        pnlStandard.setLayout(pnlStandardLayout);
        pnlStandardLayout.setHorizontalGroup(
            pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStandardLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlStandardLayout.createSequentialGroup()
                        .addGroup(pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnlStandardLayout.createSequentialGroup()
                                .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStandardLayout.createSequentialGroup()
                                .addComponent(btnCA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnFact, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStandardLayout.createSequentialGroup()
                        .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSignFlip, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStandardLayout.createSequentialGroup()
                        .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn1OverX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlStandardLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPower)))
                .addGap(31, 31, 31))
        );
        pnlStandardLayout.setVerticalGroup(
            pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlStandardLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMultiply, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn1OverX, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn4, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn5, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn6, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDivide, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPower, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn7, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn9, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPlus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSignFlip, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn0, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEqual, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMinus, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFact, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlStandardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCA, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCE, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(pnlStandard);
        pnlStandard.setBounds(10, 60, 310, 300);

        btnAsin.setText("asin");
        btnAsin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsinActionPerformed(evt);
            }
        });

        btnSin.setText("sin");
        btnSin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSinActionPerformed(evt);
            }
        });

        btnCos.setText("cos");
        btnCos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCosActionPerformed(evt);
            }
        });

        btnAcos.setText("acos");
        btnAcos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcosActionPerformed(evt);
            }
        });

        btnTan.setText("tan");
        btnTan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTanActionPerformed(evt);
            }
        });

        btnAtan.setText("atan");
        btnAtan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtanActionPerformed(evt);
            }
        });

        btnPi.setText("PI");
        btnPi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPiActionPerformed(evt);
            }
        });

        btnE.setText("E");
        btnE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlExtendedLayout = new javax.swing.GroupLayout(pnlExtended);
        pnlExtended.setLayout(pnlExtendedLayout);
        pnlExtendedLayout.setHorizontalGroup(
            pnlExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtendedLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlExtendedLayout.createSequentialGroup()
                        .addComponent(btnSin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAsin, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlExtendedLayout.createSequentialGroup()
                        .addComponent(btnCos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlExtendedLayout.createSequentialGroup()
                        .addComponent(btnTan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlExtendedLayout.createSequentialGroup()
                        .addComponent(btnPi, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlExtendedLayout.setVerticalGroup(
            pnlExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlExtendedLayout.createSequentialGroup()
                .addGroup(pnlExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSin, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                    .addComponent(btnAsin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAcos, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAtan, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlExtendedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnE, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        getContentPane().add(pnlExtended);
        pnlExtended.setBounds(340, 70, 170, 230);

        grpMode.add(radRadians);
        radRadians.setText("Radians");
        radRadians.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radRadiansItemStateChanged(evt);
            }
        });
        getContentPane().add(radRadians);
        radRadians.setBounds(460, 30, 100, 23);

        grpMode.add(radDegrees);
        radDegrees.setSelected(true);
        radDegrees.setText("Degrees");
        radDegrees.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                radDegreesItemStateChanged(evt);
            }
        });
        getContentPane().add(radDegrees);
        radDegrees.setBounds(350, 30, 100, 23);

        mnuView.setText("View");

        grpView.add(mnuBasic);
        mnuBasic.setMnemonic('B');
        mnuBasic.setSelected(true);
        mnuBasic.setText("Basic");
        mnuView.add(mnuBasic);

        grpView.add(mnuExtended);
        mnuExtended.setMnemonic('E');
        mnuExtended.setText("Extended");
        mnuExtended.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuExtendedItemStateChanged(evt);
            }
        });
        mnuView.add(mnuExtended);

        jMenuBar1.add(mnuView);

        mnuFont.setText("Font");

        mnuPlain.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        grpFont.add(mnuPlain);
        mnuPlain.setSelected(true);
        mnuPlain.setText("Plain");
        mnuPlain.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                mnuPlainItemStateChanged(evt);
            }
        });
        mnuFont.add(mnuPlain);

        mnuBold.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        grpFont.add(mnuBold);
        mnuBold.setText("Bold");
        mnuBold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBoldActionPerformed(evt);
            }
        });
        mnuFont.add(mnuBold);

        jMenuBar1.add(mnuFont);

        mnuRound.setText("Round");

        grpRound.add(rnd0);
        rnd0.setText("0");
        rnd0.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd0ItemStateChanged(evt);
            }
        });
        rnd0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rnd0ActionPerformed(evt);
            }
        });
        mnuRound.add(rnd0);

        grpRound.add(rnd1);
        rnd1.setText("1");
        rnd1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd1ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd1);

        grpRound.add(rnd2);
        rnd2.setText("2");
        rnd2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd2ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd2);

        grpRound.add(rnd3);
        rnd3.setText("3");
        rnd3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd3ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd3);

        grpRound.add(rnd4);
        rnd4.setText("4");
        rnd4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd4ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd4);

        grpRound.add(rnd5);
        rnd5.setText("5");
        rnd5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd5ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd5);

        grpRound.add(rnd6);
        rnd6.setText("6");
        rnd6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd6ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd6);

        grpRound.add(rnd7);
        rnd7.setText("7");
        rnd7.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd7ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd7);

        grpRound.add(rnd8);
        rnd8.setText("8");
        rnd8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd8ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd8);

        grpRound.add(rnd9);
        rnd9.setText("9");
        rnd9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                rnd9ItemStateChanged(evt);
            }
        });
        mnuRound.add(rnd9);

        jMenuBar1.add(mnuRound);

        mnuHelp.setText("Help");

        mnuAbout.setMnemonic('a');
        mnuAbout.setText("About");
        mnuAbout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuAboutActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuAbout);

        mnuHotKeys.setMnemonic('k');
        mnuHotKeys.setText("Hot Keys");
        mnuHotKeys.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHotKeysActionPerformed(evt);
            }
        });
        mnuHelp.add(mnuHotKeys);

        jMenuBar1.add(mnuHelp);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInOutActionPerformed

    private void mnuBoldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBoldActionPerformed
        // TODO add your handling code here:
        //font Bold call
        Menus bold=new Menus();
        if(mnuBold.isSelected()){
            bold.toBold(txtInOut);
        }
   
    }//GEN-LAST:event_mnuBoldActionPerformed

    private void mnuExtendedItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuExtendedItemStateChanged
        // TODO add your handling code here:
        if(mnuExtended.isSelected()){
            this.setSize(565,425);
        }
        else{
            this.setSize(350,435);
        }
    }//GEN-LAST:event_mnuExtendedItemStateChanged

    private void mnuPlainItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_mnuPlainItemStateChanged
        // TODO add your handling code here:
            Menus bold=new Menus();
            if(mnuPlain.isSelected()){
                bold.toPlain(txtInOut);
        }
    }//GEN-LAST:event_mnuPlainItemStateChanged

    
    
    private void rnd0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rnd0ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rnd0ActionPerformed
Menus round = new Menus();     //Instance from Menus class for rounding
    private void rnd9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd9ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd9, txtInOut);
    }//GEN-LAST:event_rnd9ItemStateChanged

    private void rnd8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd8ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd8, txtInOut);
    }//GEN-LAST:event_rnd8ItemStateChanged

    private void rnd7ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd7ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd7, txtInOut);
    }//GEN-LAST:event_rnd7ItemStateChanged

    private void rnd6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd6ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd6, txtInOut);
    }//GEN-LAST:event_rnd6ItemStateChanged

    private void rnd5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd5ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd5, txtInOut);
    }//GEN-LAST:event_rnd5ItemStateChanged

    private void rnd4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd4ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd4, txtInOut);
    }//GEN-LAST:event_rnd4ItemStateChanged

    private void rnd3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd3ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd3, txtInOut);
    }//GEN-LAST:event_rnd3ItemStateChanged

    private void rnd2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd2ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd2, txtInOut);
    }//GEN-LAST:event_rnd2ItemStateChanged

    private void rnd1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd1ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd1, txtInOut);
    }//GEN-LAST:event_rnd1ItemStateChanged

    private void rnd0ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_rnd0ItemStateChanged
        // TODO add your handling code here:
        round.round(rnd0, txtInOut);
    }//GEN-LAST:event_rnd0ItemStateChanged

    private void mnuHotKeysActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHotKeysActionPerformed
        // TODO add your handling code here:
        String hotKeys="A - About \nK - Hot keys \nCtrl+P - Plain Font \nCtrl+B - Bold Font \nB - Basic view \nE - Extended view \nAlt+P - PI \nAlt+E - E";
        msgHelp.showMessageDialog(this,hotKeys,"Title",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuHotKeysActionPerformed

    private void mnuAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuAboutActionPerformed
        // TODO add your handling code here:
        String project = "Calculator App \nCreated By: Steven Youhana \n01/02/2017";
        msgHelp.showMessageDialog(this,project,"About",javax.swing.JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_mnuAboutActionPerformed

    
    Buttons b = new Buttons();      //instance of Buttons classs
    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
        // TODO add your handling code here:

        b.numberButonsTxt(btn1, txtInOut);
    }//GEN-LAST:event_btn1ActionPerformed

    private void btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2ActionPerformed
        // TODO add your handling code here:
        
        b.numberButonsTxt(btn2, txtInOut);
        
    }//GEN-LAST:event_btn2ActionPerformed

    private void btn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3ActionPerformed
        // TODO add your handling code here:
        
        b.numberButonsTxt(btn3, txtInOut);
    }//GEN-LAST:event_btn3ActionPerformed

    private void btn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn4ActionPerformed
        // TODO add your handling code here:
         
        b.numberButonsTxt(btn4, txtInOut);  
    }//GEN-LAST:event_btn4ActionPerformed

    private void btn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn5ActionPerformed
        // TODO add your handling code here:
        
        b.numberButonsTxt(btn5, txtInOut);
    }//GEN-LAST:event_btn5ActionPerformed

    private void btn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn6ActionPerformed
        // TODO add your handling code here:
        
        b.numberButonsTxt(btn6,txtInOut);
    }//GEN-LAST:event_btn6ActionPerformed

    private void btn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn7ActionPerformed
        // TODO add your handling code here:
        
        b.numberButonsTxt(btn7,txtInOut);
    }//GEN-LAST:event_btn7ActionPerformed

    private void btn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn8ActionPerformed
        
        b.numberButonsTxt(btn8,txtInOut);
    }//GEN-LAST:event_btn8ActionPerformed

    private void btn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn9ActionPerformed

        b.numberButonsTxt(btn9, txtInOut);          
    }//GEN-LAST:event_btn9ActionPerformed

    private void btn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn0ActionPerformed
        
        b.numberButonsTxt(btn0,txtInOut);
    }//GEN-LAST:event_btn0ActionPerformed

    private void btnMultiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMultiplyActionPerformed
        if(!(b.operator.isEmpty())&txtInOut.getText().endsWith(b.operator)){
            txtInOut.setText(txtInOut.getText());
        }
        else{
        b.setOperator("*");
        b.calculate(btnMultiply, txtInOut);
        b.clearLastValue();
          
        b.exceptions(txtInOut);
        }
        b.exceptions(txtInOut);
    }//GEN-LAST:event_btnMultiplyActionPerformed

    private void btnDivideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDivideActionPerformed
        if(!(b.operator.isEmpty())&txtInOut.getText().endsWith(b.operator)){
            txtInOut.setText(txtInOut.getText());
        }
        else{
        b.setOperator("/");
        b.calculate(btnDivide, txtInOut);
        b.clearLastValue();
        
        b.exceptions(txtInOut);
        }
        b.exceptions(txtInOut);
    }//GEN-LAST:event_btnDivideActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        if(!(b.operator.isEmpty())&txtInOut.getText().endsWith(b.operator)){
            txtInOut.setText(txtInOut.getText());
        }
        else{
        b.setOperator("+");
        b.calculate(btnPlus, txtInOut);       
        b.clearLastValue();
        
            }
        b.exceptions(txtInOut);
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if(!(b.operator.isEmpty())&txtInOut.getText().endsWith(b.operator)){
            txtInOut.setText(txtInOut.getText());
        }
        else{
        b.setOperator("-");
        b.calculate(btnMinus,txtInOut);     
        b.clearLastValue();
        
        b.exceptions(txtInOut);
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void btnPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPointActionPerformed
        if(txtInOut.getText().equals("0")||txtInOut.getText().equals("0.0")){
            txtInOut.setText("0.0");
        }
        else{
        b.numberButonsTxt(btnPoint, txtInOut);
        }
    }//GEN-LAST:event_btnPointActionPerformed

    private void btn1OverXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1OverXActionPerformed
        b.calculateExt(btn1OverX, txtInOut);
        
    }//GEN-LAST:event_btn1OverXActionPerformed

    private void btnPowerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPowerActionPerformed
        b.calculateExt(btnPower, txtInOut);
       
    }//GEN-LAST:event_btnPowerActionPerformed

    private void btnSignFlipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignFlipActionPerformed
        b.calculateExt(btnSignFlip, txtInOut);
    }//GEN-LAST:event_btnSignFlipActionPerformed

    private void btnFactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFactActionPerformed
        b.fact(txtInOut);
        
    }//GEN-LAST:event_btnFactActionPerformed

    private void btnEqualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEqualActionPerformed
        // TODO add your handling code here:
    b.calculate(btnEqual, txtInOut);
    b.exceptions(txtInOut);
            
    }//GEN-LAST:event_btnEqualActionPerformed

    private void btnCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCAActionPerformed
    b.otherButtons(btnCA, txtInOut);
    }//GEN-LAST:event_btnCAActionPerformed

    private void btnCEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCEActionPerformed

    b.otherButtons(btnCE, txtInOut);
    }//GEN-LAST:event_btnCEActionPerformed

    private void btnSinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSinActionPerformed
        b.calculateExt(btnSin, txtInOut);
    }//GEN-LAST:event_btnSinActionPerformed

    private void radDegreesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radDegreesItemStateChanged
        if(radDegrees.isSelected()){
            b.angleMode="Degrees";
        }
    }//GEN-LAST:event_radDegreesItemStateChanged

    private void radRadiansItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_radRadiansItemStateChanged
        b.angleMode="Radians";
    }//GEN-LAST:event_radRadiansItemStateChanged

    private void btnCosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCosActionPerformed
        b.calculateExt(btnCos, txtInOut);
    }//GEN-LAST:event_btnCosActionPerformed

    private void btnTanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTanActionPerformed
        b.calculateExt(btnTan, txtInOut);
    }//GEN-LAST:event_btnTanActionPerformed

    private void btnAsinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsinActionPerformed
        b.calculateExt(btnAsin, txtInOut);
    }//GEN-LAST:event_btnAsinActionPerformed

    private void btnAcosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcosActionPerformed
        b.calculateExt(btnAcos, txtInOut);
    }//GEN-LAST:event_btnAcosActionPerformed

    private void btnAtanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtanActionPerformed
        b.calculateExt(btnAtan, txtInOut);
    }//GEN-LAST:event_btnAtanActionPerformed

    private void btnPiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPiActionPerformed
        b.calculateExt(btnPi, txtInOut);
    }//GEN-LAST:event_btnPiActionPerformed

    private void btnEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEActionPerformed
        b.calculateExt(btnE, txtInOut);
    }//GEN-LAST:event_btnEActionPerformed

    private void txtInOutKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInOutKeyTyped

    }//GEN-LAST:event_txtInOutKeyTyped

    private void txtInOutKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInOutKeyPressed

    }//GEN-LAST:event_txtInOutKeyPressed

    private void txtInOutKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInOutKeyReleased
        
        if(txtInOut.getText().contains("+")){
            b.setOperator("+");
        }
        if(txtInOut.getText().contains("-")){
            b.setOperator("-");
        }
        if(txtInOut.getText().contains("*")){
            b.setOperator("*");
        }
        if(txtInOut.getText().contains("/")){
            b.setOperator("/");
        }
    }//GEN-LAST:event_txtInOutKeyReleased

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculatorAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculatorAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculatorAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculatorAppFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculatorAppFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn0;
    private javax.swing.JButton btn1;
    private javax.swing.JButton btn1OverX;
    private javax.swing.JButton btn2;
    private javax.swing.JButton btn3;
    private javax.swing.JButton btn4;
    private javax.swing.JButton btn5;
    private javax.swing.JButton btn6;
    private javax.swing.JButton btn7;
    private javax.swing.JButton btn8;
    private javax.swing.JButton btn9;
    private javax.swing.JButton btnAcos;
    private javax.swing.JButton btnAsin;
    private javax.swing.JButton btnAtan;
    private javax.swing.JButton btnCA;
    private javax.swing.JButton btnCE;
    private javax.swing.JButton btnCos;
    private javax.swing.JButton btnDivide;
    private javax.swing.JButton btnE;
    private javax.swing.JButton btnEqual;
    private javax.swing.JButton btnFact;
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnMultiply;
    private javax.swing.JButton btnPi;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnPoint;
    private javax.swing.JButton btnPower;
    private javax.swing.JButton btnSignFlip;
    private javax.swing.JButton btnSin;
    private javax.swing.JButton btnTan;
    private javax.swing.ButtonGroup grpFont;
    private javax.swing.ButtonGroup grpMode;
    private javax.swing.ButtonGroup grpRound;
    private javax.swing.ButtonGroup grpView;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnuAbout;
    private javax.swing.JRadioButtonMenuItem mnuBasic;
    private javax.swing.JRadioButtonMenuItem mnuBold;
    private javax.swing.JRadioButtonMenuItem mnuExtended;
    private javax.swing.JMenu mnuFont;
    private javax.swing.JMenu mnuHelp;
    private javax.swing.JMenuItem mnuHotKeys;
    private javax.swing.JRadioButtonMenuItem mnuPlain;
    private javax.swing.JMenu mnuRound;
    private javax.swing.JMenu mnuView;
    private javax.swing.JOptionPane msgHelp;
    private javax.swing.JPanel pnlExtended;
    private javax.swing.JPanel pnlStandard;
    private javax.swing.JRadioButton radDegrees;
    private javax.swing.JRadioButton radRadians;
    private javax.swing.JRadioButtonMenuItem rnd0;
    private javax.swing.JRadioButtonMenuItem rnd1;
    private javax.swing.JRadioButtonMenuItem rnd2;
    private javax.swing.JRadioButtonMenuItem rnd3;
    private javax.swing.JRadioButtonMenuItem rnd4;
    private javax.swing.JRadioButtonMenuItem rnd5;
    private javax.swing.JRadioButtonMenuItem rnd6;
    private javax.swing.JRadioButtonMenuItem rnd7;
    private javax.swing.JRadioButtonMenuItem rnd8;
    private javax.swing.JRadioButtonMenuItem rnd9;
    private javax.swing.JTextField txtInOut;
    // End of variables declaration//GEN-END:variables
}
